"""add username field

Revision ID: a88c1935fe19
Revises: 24562a7378a8
Create Date: 2025-02-23 14:24:53.902896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a88c1935fe19'
down_revision: Union[str, None] = '24562a7378a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))

    # Atualiza os registros existentes com usernames únicos
    from sqlalchemy import table, column, String
    users_table = table("users", column("id", sa.Integer), column("username", String))

    op.execute("UPDATE users SET username = 'user_' || id WHERE username IS NULL")

    # Agora sim, torna a coluna NOT NULL
    op.alter_column("users", "username", nullable=False)

    # Adiciona índice único corretamente
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
